apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxtest-deployment
spec:
  selector:
    matchLabels:
      app: nginxtest
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
      - name: nginxtest
        image: acrbvgtestnortheu01.azurecr.io/bvg-test/nginxhallowelt:latest
        #image: bvg-test/nginxhallowelt:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxtest-front
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginxtest
  type: LoadBalancer
