apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxtest-deployment
spec:
  selector:
    matchLabels:
      app: nginxtest
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
      - name: nginxtest
        image: image: $(acrName)/nginxhallowelt
        ports:
        - containerPort: 80
        env:
        - name: acrName
          valueFrom:
            configMapKeyRef:
              name: acr-config
              key: acrName
---
apiVersion: v1
kind: Service
metadata:
  name: nginxtest-front
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginxtest
  type: LoadBalancer
